setjmp的机制及lua中的异常
====
setjmp/longjmp是C标准的函数，常用的做法是用来实现异常/跳转。原型如下：

* int setjmp(jmp_buf env);
* int longjmp(jmp_buf env, int err);

这组函数依赖于`jmp_buf`的变量类型，从接口声明看，
`jmp_buf`是值类型的，但每次调用setjmp都会把当前的各个寄存器值包括PC保存起来，
供以后longjmp来恢复，所以这个`jmp_buf`一定是指针语义的。
看了GCC 3.4.5的定义，将宏简化之后就是 typedef int `jmp_buf`[16];
也就是说`jmp_buf`类型其实是个数组，而数组在传参时又是作为指针来处理，
所以setjmp能改变`jmp_buf`所对应的值，之后的longjmp才能恢复回来。
实测在32位的XP系统上，只用了0~6共7个值，其余都是置0。

如果没有setjmp就直接longjmp，因为PC值和各种寄存器值一定是乱的，
必然导致系统崩溃。调试模式下是ntdll下抛异常。
而每一次的setjmp都将当前状态写入到jmp_buf中并返回0，
因此多次调用setjmp以后，longjmp会回到最后一次setjmp的地方。

再说说setjmp在lua中的应用。

lua在内部执行操作时，大都是调用luaD\_pcall，
这内部调用到了luaD\_rawrunprotected，在内部会进入LUAI\_TRY这个宏。
如果用C++编译，这个宏就被展开成try{}块；如果是C，
这个宏就被展开成if (setjmp() == 0) {action}这样的形式。
jmp\_buf的值会随着L带到action中，一旦发生无法补救的错误，
就会通过luaD\_throw函数，在判断了存在jmp\_buf后，
再调用LUAI\_THROW宏，实质就是longjmp的形式直接返回。
由于先判断了L中是否有jum\_buf，也就不会有异常的死机问题。

Lua的语法层面并不支持try/catch/throw这种显式的异常处理方式，
但是做一些不符合规定的操作，比如数字加nil，
字符串和nil拼接等等动作，Lua会执行出错，
如果不是在pcall内执行，导致程序提前终止，
这其实就是一种变相的固定类型的异常，
只是自定义异常类这块功能没有开放罢了。

只有系统自带的操作，在执行非法时抛出个可捕获的异常，
用pcall/xpcall来模拟try/catch，而用类似`1+nil`的方式模拟throw。
要想程序能够跑完，就要时刻注意用pcall的方式把函数执行做个封装，
而如果想提前终止，也可以用故意写非法语句来达到类似的效果。
但是写的非法语句毕竟不能携带自定义信息，只能靠代码行号来反推，
效果上就差强人意了。

